apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-finance
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    repoURL: git@github.com:growcodelabs/infra.git
    targetRevision: main
    path: manifests/apps/app-finance
  destination:
    server: https://kubernetes.default.svc
    namespace: app-finance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
