apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-finance
  namespace: app-finance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-finance
  template:
    metadata:
      labels:
        app: app-finance
    spec:
      nodeSelector:
        workload: apps
      imagePullSecrets:
        - name: registry-growcodelabs
      containers:
        - name: app-finance
          image: registry.digitalocean.com/growcodelabs/app-finance:13a9bcaab95cea425e1e10cc03c52b17aa576556
          envFrom:
            - secretRef:
                name: app-finance
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
