apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: app-finance-ci
  namespace: argo
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  workflowTemplateRef:
    name: app-finance-ci
