crds:
  upgradeJob:
    image:
      repository: docker.io/bitnami/kubectl
      tag: latest

server:
  authModes:
    - sso
  sso:
    issuer: https://argocd.growcodelabs.com/api/dex
    clientId:
      name: argo-workflows-sso
      key: client-id
    clientSecret:
      name: argo-workflows-sso
      key: client-secret
    redirectUrl: https://wf.growcodelabs.com/oauth2/callback
    scopes:
      - openid
      - profile
      - email
      - groups
    rbac:
      enabled: true
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-to-https@kubernetescrd
    hosts:
      - wf.growcodelabs.com
    tls:
      - hosts:
          - wf.growcodelabs.com
        secretName: argo-workflows-tls

workflow:
  serviceAccount:
    create: true
  rbac:
    create: true

controller:
  workflowNamespaces:
    - argo
