crds:
  upgradeJob:
    image:
      repository: docker.io/bitnami/kubectl
      tag: latest

server:
  authModes:
    - server

workflow:
  serviceAccount:
    create: true
  rbac:
    create: true

controller:
  workflowNamespaces:
    - argo
